### ISSUE TITLE
Why don't you update shape code when editing shape

### ISSUE THREAD

**Issue by ghy0324** [stevliu/editnerf#2]
As is mentioned in your paper, you update `F_rad` and color code `z^c` when editing colors, while you only update `F_fuse` and `F_dens` when editing shape.
I'm wondering why don't you also update shape code `z^s` when editing shape.

**Comment by stevliu** [comment]
Hi! We find that updating the shape code as well doesn't improve the edit quality noticeably. Also, updating the shape code would make the optimization process slower: because the shape code is fed into the beginning of the network, you can't cache intermediate features during optimization, and you need to backprop through the whole network.
